INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Bending the knee in sitting','To improve your ability to bend your knee in preparation for standing.',4,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Bending the wrist to a target','To improve your ability to straighten your wrist.',5,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Abducting the thumb to a target','To improve your ability to open your thumb to help pick up a cup or glass.',6,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Elbow strengthening in lying','To strengthen the muscles that straighten your elbow',7,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Elbow bending and straightening','To improve your ability to bend and straighten your elbow.',8,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Finger strenthening','To strengthen the muscles that straighten your fingers.',9,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Forearm movements','To improve your ability to turn your palm up and down.',10,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Hand behind back','To stretch or maintain range in your shoulders.',11,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Hand behind head','To stretch or maintain range in your shoulders.',12,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Full fist strengthening with putty or stress ball','To strengthen your hand grip.',13,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Hand webspace stretch','To stretch or maintain range in your hand.',14,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Opposition of thumb to index finger','To improve your ability to manipulate objects with your hand.',15,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Thumb abduction','To improve your ability to open your thumb.',16,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Pouring water from one cup to another','To improve your ability to manipulate objects with your hand.',17,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Taking a cup to the mouth','To improve your ability to bring a cup to your mouth.',18,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Pressing numbers on a phone','To improve your ability to manipulate objects with your hand.',19,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Wrist flexion and extension','To improve your ability to bend and straighten your wrist.',20,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Using a pen','To improve your ability to write.',21,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Reaching forward to an object','To improve your ability to pick up an object.',22,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Shoulder retractor strengthening in sitting','To strengthen the muscles at the back of your shoulder.',23,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Neck lateral flexor stretch','To stretch or maintain length in the muscles at the side of your neck.',24,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Neck flexor/extensor stretch','To stretch or maintain range of your neck.',25,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Head rotation','To improve your head rotation.',26,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Hip abductor/adductor strengthening in supine','To strengthen the muscles at the side and on the inside of your hip.',27,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Hip abduction in sidelying','To strengthen the muscles at the side of your hip.',28,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Hip flexor strengthening in sitting','To strengthen the muscles at the front of your hip.',29,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Inner range quads over a roll','To strengthen the thigh muscles.',30,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Knee extension in sitting','To strengthen your thigh muscles.',31,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Straight leg raise','To strengthen the muscles at the front of your hip and knee.',32,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Static quads','To strengthen the thigh muscles.',33,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Hip and knee flexion in supine','To increase movement of the hip and knee.',34,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Hip flexor strengthening in supine','To strengthen the muscles at the front of your hip.',35,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Moving across the bed','To improve your ability to move in bed.',36,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Bridging','To strengthen the muscles at the back of your hip.',37,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Heel raises','To strengthen your calf muscles.',38,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Squat in standing','To strengthen the muscles that straighten your leg.',39,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Marching on the spot','To improve your ability to walk.',40,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Sit to stand','To improve your ability to stand up or sit down.',41,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Ankle plantarflexor stretch using a pillow','To stretch or maintain range in your ankle.',42,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Passive shoulder flexion','To stretch or maintain range of the shoulder joint.',43,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Passive shoulder abduction','To stretch or maintain range of the shoulder joint.',44,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Passive wrist flexion and extension','To stretch or maintain range of the wrist joint.',45,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Passive finger and hand movements','To stretch or maintain range of the finger, hand and wrist joints.',46,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Upper limb passive movements','To stretch or maintain length of the upper limb muscles.',47,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Assisted ankle plantarflexor stretch','To induce transient increases in the extensibility of the muscles at the back of your ankle.',48,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Elbow extensor strengthening in sitting using theraband','To strengthen your triceps.',49,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Elbow extensor strengthening in supine using theraband','To strengthen your triceps.',50,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Elbow flexor strengthening in sitting using theraband','To strengthen your biceps.',51,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Elbow flexor strengthening in supine using theraband','To strengthen your biceps.',52,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Hip abduction in sitting with theraband','To strengthen your hip muscles',53,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Knee extension with Theraband','To strengthen your thigh muscles.',54,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Knee extensor strengthening in sitting using theraband','To strengthen the muscles at the front of your thigh.',55,2);
INSERT INTO Exercises(ExerciseName,ExerciseDescription,Image,Gif) VALUES ('Shoulder rotator strengthening sitting using theraband','To strengthen your shoulder muscles.',56,2);
